// Code generated by sqlitegen. DO NOT EDIT.
package sqlite

import (
	"fmt"
	"sync"

	"github.com/bnema/purego-sqlite/internal/capi"
	"github.com/bnema/purego-sqlite/internal/core"
	"github.com/bnema/purego-sqlite/internal/loader"
	portin "github.com/bnema/purego-sqlite/internal/ports/in"
	portout "github.com/bnema/purego-sqlite/internal/ports/out"
)

// DB is the public database interface.
type DB = portin.DB

// Stmt is the public prepared statement interface.
type Stmt = portin.Stmt

// Rows is the public result set interface.
type Rows = portin.Rows

// Result is the public exec result interface.
type Result = portin.Result

// bridge is the singleton CAPI implementation, initialized by first Open call.
var (
	bridge   portout.CAPI
	initOnce sync.Once
	initErr  error
)

// Open opens a SQLite database at the given path.
func Open(dsn string) (DB, error) {
	initOnce.Do(func() {
		handle, err := loader.Open()
		if err != nil {
			initErr = fmt.Errorf("sqlite: %w", err)
			return
		}
		capi.Register(handle)
		bridge = capi.NewBridge()
	})
	if initErr != nil {
		return nil, initErr
	}
	return core.OpenDB(bridge, dsn)
}
