// Code generated by sqlitegen. DO NOT EDIT.
package sqlite

import (
	"fmt"

	"github.com/bnema/purego-sqlite/internal/capi"
	"github.com/bnema/purego-sqlite/internal/core"
	"github.com/bnema/purego-sqlite/internal/loader"
	portin "github.com/bnema/purego-sqlite/internal/ports/in"
	portout "github.com/bnema/purego-sqlite/internal/ports/out"
)

// DB is the public database interface.
type DB = portin.DB

// Stmt is the public prepared statement interface.
type Stmt = portin.Stmt

// Rows is the public result set interface.
type Rows = portin.Rows

// Result is the public exec result interface.
type Result = portin.Result

// bridge is the singleton CAPI implementation, initialized by first Open call.
var bridge portout.CAPI

// Open opens a SQLite database at the given path.
func Open(dsn string) (DB, error) {
	if bridge == nil {
		handle, err := loader.Open()
		if err != nil {
			return nil, fmt.Errorf("sqlite: %w", err)
		}
		capi.Register(handle)
		bridge = capi.NewBridge()
	}
	return core.OpenDB(bridge, dsn)
}
