// Code generated by sqlitegen. DO NOT EDIT.
package capi

import (
	"unsafe"
)

var _ unsafe.Pointer

var Sqlite3Libversion func() string
var Sqlite3Sourceid func() string
var Sqlite3LibversionNumber func() int32
var Sqlite3CompileoptionUsed func(zOptName string) int32
var Sqlite3CompileoptionGet func(n int32) string
var Sqlite3Threadsafe func() int32
var Sqlite3Close func(arg0 unsafe.Pointer) int32
var Sqlite3CloseV2 func(arg0 unsafe.Pointer) int32
var Sqlite3Exec func(arg0 unsafe.Pointer, sQL string, arg1 unsafe.Pointer, arg2 unsafe.Pointer, errmsg unsafe.Pointer) int32
var Sqlite3Initialize func() int32
var Sqlite3Shutdown func() int32
var Sqlite3OsInit func() int32
var Sqlite3OsEnd func() int32
var Sqlite3ExtendedResultCodes func(arg0 unsafe.Pointer, onoff int32) int32
var Sqlite3LastInsertRowid func(arg0 unsafe.Pointer) int64
var Sqlite3SetLastInsertRowid func(arg0 unsafe.Pointer, sqlite3Int64 uintptr)
var Sqlite3Changes func(arg0 unsafe.Pointer) int32
var Sqlite3Changes64 func(arg0 unsafe.Pointer) int64
var Sqlite3TotalChanges func(arg0 unsafe.Pointer) int32
var Sqlite3TotalChanges64 func(arg0 unsafe.Pointer) int64
var Sqlite3Interrupt func(arg0 unsafe.Pointer)
var Sqlite3IsInterrupted func(arg0 unsafe.Pointer) int32
var Sqlite3Complete func(sQL string) int32
var Sqlite3Complete16 func(sQL unsafe.Pointer) int32
var Sqlite3BusyHandler func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3BusyTimeout func(arg0 unsafe.Pointer, ms int32) int32
var Sqlite3SetlkTimeout func(arg0 unsafe.Pointer, ms int32, flags int32) int32
var Sqlite3GetTable func(dB unsafe.Pointer, zSql string, pazResult unsafe.Pointer, pnRow unsafe.Pointer, pnColumn unsafe.Pointer, pzErrmsg unsafe.Pointer) int32
var Sqlite3FreeTable func(result unsafe.Pointer)
var Sqlite3Vmprintf func(arg0 string, vaList uintptr) string
var Sqlite3Vsnprintf func(arg0 uintptr, arg1 string, arg2 string, vaList uintptr) string
var Sqlite3Malloc func(arg0 uintptr) unsafe.Pointer
var Sqlite3Malloc64 func(sqlite3Uint64 uintptr) unsafe.Pointer
var Sqlite3Realloc func(arg0 unsafe.Pointer, arg1 uintptr) unsafe.Pointer
var Sqlite3Realloc64 func(arg0 unsafe.Pointer, sqlite3Uint64 uintptr) unsafe.Pointer
var Sqlite3Free func(arg0 unsafe.Pointer)
var Sqlite3Msize func(arg0 unsafe.Pointer) uint64
var Sqlite3MemoryUsed func() int64
var Sqlite3MemoryHighwater func(resetFlag int32) int64
var Sqlite3Randomness func(n int32, p unsafe.Pointer)
var Sqlite3SetAuthorizer func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, pUserData unsafe.Pointer) int32
var Sqlite3Trace func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3Profile func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3TraceV2 func(arg0 unsafe.Pointer, uMask uintptr, arg1 unsafe.Pointer, pCtx unsafe.Pointer) int32
var Sqlite3ProgressHandler func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer, arg3 unsafe.Pointer)
var Sqlite3Open func(filename string, ppDb unsafe.Pointer) int32
var Sqlite3Open16 func(filename unsafe.Pointer, ppDb unsafe.Pointer) int32
var Sqlite3OpenV2 func(filename string, ppDb unsafe.Pointer, flags int32, zVfs string) int32
var Sqlite3UriParameter func(z uintptr, zParam string) string
var Sqlite3UriBoolean func(z uintptr, zParam string, bDefault int32) int32
var Sqlite3UriInt64 func(sqlite3Filename uintptr, arg0 string, sqlite3Int64 uintptr) int64
var Sqlite3UriKey func(z uintptr, n int32) string
var Sqlite3FilenameDatabase func(sqlite3Filename uintptr) string
var Sqlite3FilenameJournal func(sqlite3Filename uintptr) string
var Sqlite3FilenameWAL func(sqlite3Filename uintptr) string
var Sqlite3DatabaseFileObject func(arg0 string) unsafe.Pointer
var Sqlite3CreateFilename func(zDatabase string, zJournal string, zWal string, nParam int32, azParam unsafe.Pointer) uintptr
var Sqlite3FreeFilename func(sqlite3Filename uintptr)
var Sqlite3Errcode func(dB unsafe.Pointer) int32
var Sqlite3ExtendedErrcode func(dB unsafe.Pointer) int32
var Sqlite3Errmsg func(arg0 unsafe.Pointer) string
var Sqlite3Errmsg16 func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3Errstr func(arg0 uintptr) string
var Sqlite3ErrorOffset func(dB unsafe.Pointer) int32
var Sqlite3SetErrmsg func(dB unsafe.Pointer, errcode int32, zErrMsg string) int32
var Sqlite3Limit func(arg0 unsafe.Pointer, iD int32, newVal int32) int32
var Sqlite3Prepare func(dB unsafe.Pointer, zSql string, nByte int32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3PrepareV2 func(dB unsafe.Pointer, zSql string, nByte int32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3PrepareV3 func(dB unsafe.Pointer, zSql string, nByte int32, prepFlags uint32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3Prepare16 func(dB unsafe.Pointer, zSql unsafe.Pointer, nByte int32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3Prepare16V2 func(dB unsafe.Pointer, zSql unsafe.Pointer, nByte int32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3Prepare16V3 func(dB unsafe.Pointer, zSql unsafe.Pointer, nByte int32, prepFlags uint32, ppStmt unsafe.Pointer, pzTail unsafe.Pointer) int32
var Sqlite3SQL func(pStmt unsafe.Pointer) string
var Sqlite3ExpandedSQL func(pStmt unsafe.Pointer) string
var Sqlite3NormalizedSQL func(pStmt unsafe.Pointer) string
var Sqlite3StmtReadonly func(pStmt unsafe.Pointer) int32
var Sqlite3StmtIsexplain func(pStmt unsafe.Pointer) int32
var Sqlite3StmtExplain func(pStmt unsafe.Pointer, eMode int32) int32
var Sqlite3StmtBusy func(arg0 unsafe.Pointer) int32
var Sqlite3BindBlob func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer, n int32, arg3 unsafe.Pointer) int32
var Sqlite3BindBlob64 func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer, sqlite3Uint64 uintptr, arg3 unsafe.Pointer) int32
var Sqlite3BindDouble func(arg0 unsafe.Pointer, arg1 uintptr, arg2 uintptr) int32
var Sqlite3BindInt func(arg0 unsafe.Pointer, arg1 uintptr, arg2 uintptr) int32
var Sqlite3BindInt64 func(arg0 unsafe.Pointer, arg1 uintptr, sqlite3Int64 uintptr) int32
var Sqlite3BindNull func(arg0 unsafe.Pointer, arg1 uintptr) int32
var Sqlite3BindText func(arg0 unsafe.Pointer, arg1 uintptr, arg2 string, arg3 uintptr, arg4 unsafe.Pointer) int32
var Sqlite3BindText16 func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer, arg3 uintptr, arg4 unsafe.Pointer) int32
var Sqlite3BindText64 func(arg0 unsafe.Pointer, arg1 uintptr, arg2 string, sqlite3Uint64 uintptr, arg3 unsafe.Pointer, encoding uintptr) int32
var Sqlite3BindValue func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer) int32
var Sqlite3BindPointer func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer, arg3 string, arg4 unsafe.Pointer) int32
var Sqlite3BindZeroblob func(arg0 unsafe.Pointer, arg1 uintptr, n int32) int32
var Sqlite3BindZeroblob64 func(arg0 unsafe.Pointer, arg1 uintptr, sqlite3Uint64 uintptr) int32
var Sqlite3BindParameterCount func(arg0 unsafe.Pointer) int32
var Sqlite3BindParameterName func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3BindParameterIndex func(arg0 unsafe.Pointer, zName string) int32
var Sqlite3ClearBindings func(arg0 unsafe.Pointer) int32
var Sqlite3ColumnCount func(pStmt unsafe.Pointer) int32
var Sqlite3ColumnName func(arg0 unsafe.Pointer, n int32) string
var Sqlite3ColumnName16 func(arg0 unsafe.Pointer, n int32) unsafe.Pointer
var Sqlite3ColumnDatabaseName func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3ColumnDatabaseName16 func(arg0 unsafe.Pointer, arg1 uintptr) unsafe.Pointer
var Sqlite3ColumnTableName func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3ColumnTableName16 func(arg0 unsafe.Pointer, arg1 uintptr) unsafe.Pointer
var Sqlite3ColumnOriginName func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3ColumnOriginName16 func(arg0 unsafe.Pointer, arg1 uintptr) unsafe.Pointer
var Sqlite3ColumnDecltype func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3ColumnDecltype16 func(arg0 unsafe.Pointer, arg1 uintptr) unsafe.Pointer
var Sqlite3Step func(arg0 unsafe.Pointer) int32
var Sqlite3DataCount func(pStmt unsafe.Pointer) int32
var Sqlite3ColumnBlob func(arg0 unsafe.Pointer, iCol int32) unsafe.Pointer
var Sqlite3ColumnDouble func(arg0 unsafe.Pointer, iCol int32) float64
var Sqlite3ColumnInt func(arg0 unsafe.Pointer, iCol int32) int32
var Sqlite3ColumnInt64 func(arg0 unsafe.Pointer, iCol int32) int64
var Sqlite3ColumnText func(arg0 unsafe.Pointer, iCol int32) *byte
var Sqlite3ColumnText16 func(arg0 unsafe.Pointer, iCol int32) unsafe.Pointer
var Sqlite3ColumnValue func(arg0 unsafe.Pointer, iCol int32) unsafe.Pointer
var Sqlite3ColumnBytes func(arg0 unsafe.Pointer, iCol int32) int32
var Sqlite3ColumnBytes16 func(arg0 unsafe.Pointer, iCol int32) int32
var Sqlite3ColumnType func(arg0 unsafe.Pointer, iCol int32) int32
var Sqlite3Finalize func(pStmt unsafe.Pointer) int32
var Sqlite3Reset func(pStmt unsafe.Pointer) int32
var Sqlite3CreateFunction func(dB unsafe.Pointer, zFunctionName string, nArg int32, eTextRep int32, pApp unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3CreateFunction16 func(dB unsafe.Pointer, zFunctionName unsafe.Pointer, nArg int32, eTextRep int32, pApp unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3CreateFunctionV2 func(dB unsafe.Pointer, zFunctionName string, nArg int32, eTextRep int32, pApp unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer, arg3 unsafe.Pointer) int32
var Sqlite3CreateWindowFunction func(dB unsafe.Pointer, zFunctionName string, nArg int32, eTextRep int32, pApp unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer, arg3 unsafe.Pointer, arg4 unsafe.Pointer) int32
var Sqlite3AggregateCount func(arg0 unsafe.Pointer) int32
var Sqlite3Expired func(arg0 unsafe.Pointer) int32
var Sqlite3TransferBindings func(arg0 unsafe.Pointer, arg1 unsafe.Pointer) int32
var Sqlite3GlobalRecover func() int32
var Sqlite3ThreadCleanup func()
var Sqlite3MemoryAlarm func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, sqlite3Int64 uintptr) int32
var Sqlite3ValueBlob func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ValueDouble func(arg0 unsafe.Pointer) float64
var Sqlite3ValueInt func(arg0 unsafe.Pointer) int32
var Sqlite3ValueInt64 func(arg0 unsafe.Pointer) int64
var Sqlite3ValuePointer func(arg0 unsafe.Pointer, arg1 string) unsafe.Pointer
var Sqlite3ValueText func(arg0 unsafe.Pointer) *byte
var Sqlite3ValueText16 func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ValueText16le func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ValueText16be func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ValueBytes func(arg0 unsafe.Pointer) int32
var Sqlite3ValueBytes16 func(arg0 unsafe.Pointer) int32
var Sqlite3ValueType func(arg0 unsafe.Pointer) int32
var Sqlite3ValueNumericType func(arg0 unsafe.Pointer) int32
var Sqlite3ValueNochange func(arg0 unsafe.Pointer) int32
var Sqlite3ValueFrombind func(arg0 unsafe.Pointer) int32
var Sqlite3ValueEncoding func(arg0 unsafe.Pointer) int32
var Sqlite3ValueSubtype func(arg0 unsafe.Pointer) uint32
var Sqlite3ValueDup func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ValueFree func(arg0 unsafe.Pointer)
var Sqlite3AggregateContext func(arg0 unsafe.Pointer, nBytes int32) unsafe.Pointer
var Sqlite3UserData func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3ContextDBHandle func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3GetAuxdata func(arg0 unsafe.Pointer, n int32) unsafe.Pointer
var Sqlite3SetAuxdata func(arg0 unsafe.Pointer, n int32, arg1 unsafe.Pointer, arg2 unsafe.Pointer)
var Sqlite3GetClientdata func(arg0 unsafe.Pointer, arg1 string) unsafe.Pointer
var Sqlite3SetClientdata func(arg0 unsafe.Pointer, arg1 string, arg2 unsafe.Pointer, arg3 unsafe.Pointer) int32
var Sqlite3ResultBlob func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 uintptr, arg3 unsafe.Pointer)
var Sqlite3ResultBlob64 func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, sqlite3Uint64 uintptr, arg2 unsafe.Pointer)
var Sqlite3ResultDouble func(arg0 unsafe.Pointer, arg1 uintptr)
var Sqlite3ResultError func(arg0 unsafe.Pointer, arg1 string, arg2 uintptr)
var Sqlite3ResultError16 func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 uintptr)
var Sqlite3ResultErrorToobig func(arg0 unsafe.Pointer)
var Sqlite3ResultErrorNomem func(arg0 unsafe.Pointer)
var Sqlite3ResultErrorCode func(arg0 unsafe.Pointer, arg1 uintptr)
var Sqlite3ResultInt func(arg0 unsafe.Pointer, arg1 uintptr)
var Sqlite3ResultInt64 func(arg0 unsafe.Pointer, sqlite3Int64 uintptr)
var Sqlite3ResultNull func(arg0 unsafe.Pointer)
var Sqlite3ResultText func(arg0 unsafe.Pointer, arg1 string, arg2 uintptr, arg3 unsafe.Pointer)
var Sqlite3ResultText64 func(arg0 unsafe.Pointer, z string, n uint64, arg1 unsafe.Pointer, encoding uintptr)
var Sqlite3ResultText16 func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 uintptr, arg3 unsafe.Pointer)
var Sqlite3ResultText16le func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 uintptr, arg3 unsafe.Pointer)
var Sqlite3ResultText16be func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 uintptr, arg3 unsafe.Pointer)
var Sqlite3ResultValue func(arg0 unsafe.Pointer, arg1 unsafe.Pointer)
var Sqlite3ResultPointer func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 string, arg3 unsafe.Pointer)
var Sqlite3ResultZeroblob func(arg0 unsafe.Pointer, n int32)
var Sqlite3ResultZeroblob64 func(arg0 unsafe.Pointer, n uint64) int32
var Sqlite3ResultSubtype func(arg0 unsafe.Pointer, arg1 uintptr)
var Sqlite3CreateCollation func(arg0 unsafe.Pointer, zName string, eTextRep int32, pArg unsafe.Pointer, arg1 unsafe.Pointer) int32
var Sqlite3CreateCollationV2 func(arg0 unsafe.Pointer, zName string, eTextRep int32, pArg unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3CreateCollation16 func(arg0 unsafe.Pointer, zName unsafe.Pointer, eTextRep int32, pArg unsafe.Pointer, arg1 unsafe.Pointer) int32
var Sqlite3CollationNeeded func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3CollationNeeded16 func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3ActivateCerod func(zPassPhrase string)
var Sqlite3Sleep func(arg0 uintptr) int32
var Sqlite3Win32SetDirectory func(arg0 uintptr, zValue unsafe.Pointer) int32
var Sqlite3Win32SetDirectory8 func(arg0 uintptr, zValue string) int32
var Sqlite3Win32SetDirectory16 func(arg0 uintptr, zValue unsafe.Pointer) int32
var Sqlite3GetAutocommit func(arg0 unsafe.Pointer) int32
var Sqlite3DBHandle func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3DBName func(dB unsafe.Pointer, n int32) string
var Sqlite3DBFilename func(dB unsafe.Pointer, zDbName string) uintptr
var Sqlite3DBReadonly func(dB unsafe.Pointer, zDbName string) int32
var Sqlite3TxnState func(arg0 unsafe.Pointer, zSchema string) int32
var Sqlite3NextStmt func(pDb unsafe.Pointer, pStmt unsafe.Pointer) unsafe.Pointer
var Sqlite3CommitHook func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3RollbackHook func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3AutovacuumPages func(dB unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3UpdateHook func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3EnableSharedCache func(arg0 uintptr) int32
var Sqlite3ReleaseMemory func(arg0 uintptr) int32
var Sqlite3DBReleaseMemory func(arg0 unsafe.Pointer) int32
var Sqlite3SoftHeapLimit64 func(n int64) int64
var Sqlite3HardHeapLimit64 func(n int64) int64
var Sqlite3SoftHeapLimit func(n int32)
var Sqlite3TableColumnMetadata func(dB unsafe.Pointer, zDbName string, zTableName string, zColumnName string, pzDataType unsafe.Pointer, pzCollSeq unsafe.Pointer, pNotNull unsafe.Pointer, pPrimaryKey unsafe.Pointer, pAutoinc unsafe.Pointer) int32
var Sqlite3LoadExtension func(dB unsafe.Pointer, zFile string, zProc string, pzErrMsg unsafe.Pointer) int32
var Sqlite3EnableLoadExtension func(dB unsafe.Pointer, onoff int32) int32
var Sqlite3AutoExtension func(arg0 unsafe.Pointer) int32
var Sqlite3CancelAutoExtension func(arg0 unsafe.Pointer) int32
var Sqlite3ResetAutoExtension func()
var Sqlite3CreateModule func(dB unsafe.Pointer, zName string, p unsafe.Pointer, pClientData unsafe.Pointer) int32
var Sqlite3CreateModuleV2 func(dB unsafe.Pointer, zName string, p unsafe.Pointer, pClientData unsafe.Pointer, arg0 unsafe.Pointer) int32
var Sqlite3DropModules func(dB unsafe.Pointer, azKeep unsafe.Pointer) int32
var Sqlite3DeclareVtab func(arg0 unsafe.Pointer, zSQL string) int32
var Sqlite3OverloadFunction func(arg0 unsafe.Pointer, zFuncName string, nArg int32) int32
var Sqlite3BlobOpen func(arg0 unsafe.Pointer, zDb string, zTable string, zColumn string, iRow int64, flags int32, ppBlob unsafe.Pointer) int32
var Sqlite3BlobReopen func(arg0 unsafe.Pointer, sqlite3Int64 uintptr) int32
var Sqlite3BlobClose func(arg0 unsafe.Pointer) int32
var Sqlite3BlobBytes func(arg0 unsafe.Pointer) int32
var Sqlite3BlobRead func(arg0 unsafe.Pointer, z unsafe.Pointer, n int32, iOffset int32) int32
var Sqlite3BlobWrite func(arg0 unsafe.Pointer, z unsafe.Pointer, n int32, iOffset int32) int32
var Sqlite3VFSFind func(zVfsName string) unsafe.Pointer
var Sqlite3VFSRegister func(arg0 unsafe.Pointer, makeDflt int32) int32
var Sqlite3VFSUnregister func(arg0 unsafe.Pointer) int32
var Sqlite3MutexAlloc func(arg0 uintptr) unsafe.Pointer
var Sqlite3MutexFree func(arg0 unsafe.Pointer)
var Sqlite3MutexEnter func(arg0 unsafe.Pointer)
var Sqlite3MutexTry func(arg0 unsafe.Pointer) int32
var Sqlite3MutexLeave func(arg0 unsafe.Pointer)
var Sqlite3MutexHeld func(arg0 unsafe.Pointer) int32
var Sqlite3MutexNotheld func(arg0 unsafe.Pointer) int32
var Sqlite3DBMutex func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3FileControl func(arg0 unsafe.Pointer, zDbName string, op int32, arg1 unsafe.Pointer) int32
var Sqlite3KeywordCount func() int32
var Sqlite3KeywordName func(arg0 uintptr, arg1 unsafe.Pointer, arg2 unsafe.Pointer) int32
var Sqlite3KeywordCheck func(arg0 string, arg1 uintptr) int32
var Sqlite3StrNew func(arg0 unsafe.Pointer) unsafe.Pointer
var Sqlite3StrFinish func(arg0 unsafe.Pointer) string
var Sqlite3StrFree func(arg0 unsafe.Pointer)
var Sqlite3StrVappendf func(arg0 unsafe.Pointer, zFormat string, vaList uintptr)
var Sqlite3StrAppend func(arg0 unsafe.Pointer, zIn string, n int32)
var Sqlite3StrAppendall func(arg0 unsafe.Pointer, zIn string)
var Sqlite3StrAppendchar func(arg0 unsafe.Pointer, n int32, c uintptr)
var Sqlite3StrReset func(arg0 unsafe.Pointer)
var Sqlite3StrTruncate func(arg0 unsafe.Pointer, n int32)
var Sqlite3StrErrcode func(arg0 unsafe.Pointer) int32
var Sqlite3StrLength func(arg0 unsafe.Pointer) int32
var Sqlite3StrValue func(arg0 unsafe.Pointer) string
var Sqlite3Status func(op int32, pCurrent unsafe.Pointer, pHighwater unsafe.Pointer, resetFlag int32) int32
var Sqlite3Status64 func(op int32, pCurrent int64, pHighwater int64, resetFlag int32) int32
var Sqlite3DBStatus func(arg0 unsafe.Pointer, op int32, pCur unsafe.Pointer, pHiwtr unsafe.Pointer, resetFlg int32) int32
var Sqlite3DBStatus64 func(arg0 unsafe.Pointer, arg1 uintptr, arg2 int64, arg3 int64, arg4 uintptr) int32
var Sqlite3StmtStatus func(arg0 unsafe.Pointer, op int32, resetFlg int32) int32
var Sqlite3BackupInit func(pDest unsafe.Pointer, zDestName string, pSource unsafe.Pointer, zSourceName string) unsafe.Pointer
var Sqlite3BackupStep func(p unsafe.Pointer, nPage int32) int32
var Sqlite3BackupFinish func(p unsafe.Pointer) int32
var Sqlite3BackupRemaining func(p unsafe.Pointer) int32
var Sqlite3BackupPagecount func(p unsafe.Pointer) int32
var Sqlite3UnlockNotify func(pBlocked unsafe.Pointer, arg0 unsafe.Pointer, pNotifyArg unsafe.Pointer) int32
var Sqlite3Stricmp func(arg0 string, arg1 string) int32
var Sqlite3Strnicmp func(arg0 string, arg1 string, arg2 uintptr) int32
var Sqlite3Strglob func(zGlob string, zStr string) int32
var Sqlite3Strlike func(zGlob string, zStr string, cEsc uint32) int32
var Sqlite3WALHook func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer) unsafe.Pointer
var Sqlite3WALAutocheckpoint func(dB unsafe.Pointer, n int32) int32
var Sqlite3WALCheckpoint func(dB unsafe.Pointer, zDb string) int32
var Sqlite3WALCheckpointV2 func(dB unsafe.Pointer, zDb string, eMode int32, pnLog unsafe.Pointer, pnCkpt unsafe.Pointer) int32
var Sqlite3VtabOnConflict func(arg0 unsafe.Pointer) int32
var Sqlite3VtabNochange func(arg0 unsafe.Pointer) int32
var Sqlite3VtabCollation func(arg0 unsafe.Pointer, arg1 uintptr) string
var Sqlite3VtabDistinct func(arg0 unsafe.Pointer) int32
var Sqlite3VtabIn func(arg0 unsafe.Pointer, iCons int32, bHandle int32) int32
var Sqlite3VtabInFirst func(pVal unsafe.Pointer, ppOut unsafe.Pointer) int32
var Sqlite3VtabInNext func(pVal unsafe.Pointer, ppOut unsafe.Pointer) int32
var Sqlite3VtabRhsValue func(arg0 unsafe.Pointer, arg1 uintptr, ppVal unsafe.Pointer) int32
var Sqlite3StmtScanstatus func(pStmt unsafe.Pointer, idx int32, iScanStatusOp int32, pOut unsafe.Pointer) int32
var Sqlite3StmtScanstatusV2 func(pStmt unsafe.Pointer, idx int32, iScanStatusOp int32, flags int32, pOut unsafe.Pointer) int32
var Sqlite3StmtScanstatusReset func(arg0 unsafe.Pointer)
var Sqlite3DBCacheflush func(arg0 unsafe.Pointer) int32
var Sqlite3PreupdateHook func(dB unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer) unsafe.Pointer
var Sqlite3PreupdateOld func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer) int32
var Sqlite3PreupdateCount func(arg0 unsafe.Pointer) int32
var Sqlite3PreupdateDepth func(arg0 unsafe.Pointer) int32
var Sqlite3PreupdateNew func(arg0 unsafe.Pointer, arg1 uintptr, arg2 unsafe.Pointer) int32
var Sqlite3PreupdateBlobwrite func(arg0 unsafe.Pointer) int32
var Sqlite3SystemErrno func(arg0 unsafe.Pointer) int32
var Sqlite3SnapshotGet func(dB unsafe.Pointer, zSchema string, ppSnapshot unsafe.Pointer) int32
var Sqlite3SnapshotOpen func(dB unsafe.Pointer, zSchema string, pSnapshot unsafe.Pointer) int32
var Sqlite3SnapshotFree func(arg0 unsafe.Pointer)
var Sqlite3SnapshotCmp func(p1 unsafe.Pointer, p2 unsafe.Pointer) int32
var Sqlite3SnapshotRecover func(dB unsafe.Pointer, zDb string) int32
var Sqlite3Serialize func(dB unsafe.Pointer, zSchema string, piSize int64, mFlags uint32) *byte
var Sqlite3Deserialize func(dB unsafe.Pointer, zSchema string, pData *byte, szDb int64, szBuf int64, mFlags uintptr) int32
var Sqlite3CarrayBindV2 func(pStmt unsafe.Pointer, i int32, aData unsafe.Pointer, nData int32, mFlags int32, arg0 unsafe.Pointer, pDel unsafe.Pointer) int32
var Sqlite3CarrayBind func(pStmt unsafe.Pointer, i int32, aData unsafe.Pointer, nData int32, mFlags int32, arg0 unsafe.Pointer) int32
var Sqlite3RtreeGeometryCallback func(dB unsafe.Pointer, zGeom string, arg0 unsafe.Pointer, pContext unsafe.Pointer) int32
var Sqlite3RtreeQueryCallback func(dB unsafe.Pointer, zQueryFunc string, arg0 unsafe.Pointer, pContext unsafe.Pointer, arg1 unsafe.Pointer) int32
var Sqlite3sessionCreate func(dB unsafe.Pointer, zDb string, ppSession unsafe.Pointer) int32
var Sqlite3sessionDelete func(pSession unsafe.Pointer)
var Sqlite3sessionObjectConfig func(arg0 unsafe.Pointer, op int32, pArg unsafe.Pointer) int32
var Sqlite3sessionEnable func(pSession unsafe.Pointer, bEnable int32) int32
var Sqlite3sessionIndirect func(pSession unsafe.Pointer, bIndirect int32) int32
var Sqlite3sessionAttach func(pSession unsafe.Pointer, zTab string) int32
var Sqlite3sessionTableFilter func(pSession unsafe.Pointer, arg0 unsafe.Pointer, pCtx unsafe.Pointer)
var Sqlite3sessionChangeset func(pSession unsafe.Pointer, pnChangeset unsafe.Pointer, ppChangeset unsafe.Pointer) int32
var Sqlite3sessionChangesetSize func(pSession unsafe.Pointer) int64
var Sqlite3sessionDiff func(pSession unsafe.Pointer, zFromDb string, zTbl string, pzErrMsg unsafe.Pointer) int32
var Sqlite3sessionPatchset func(pSession unsafe.Pointer, pnPatchset unsafe.Pointer, ppPatchset unsafe.Pointer) int32
var Sqlite3sessionIsempty func(pSession unsafe.Pointer) int32
var Sqlite3sessionMemoryUsed func(pSession unsafe.Pointer) int64
var Sqlite3changesetStart func(pp unsafe.Pointer, nChangeset int32, pChangeset unsafe.Pointer) int32
var Sqlite3changesetStartV2 func(pp unsafe.Pointer, nChangeset int32, pChangeset unsafe.Pointer, flags int32) int32
var Sqlite3changesetNext func(pIter unsafe.Pointer) int32
var Sqlite3changesetOp func(pIter unsafe.Pointer, pzTab unsafe.Pointer, pnCol unsafe.Pointer, pOp unsafe.Pointer, pbIndirect unsafe.Pointer) int32
var Sqlite3changesetPk func(pIter unsafe.Pointer, pabPK unsafe.Pointer, pnCol unsafe.Pointer) int32
var Sqlite3changesetOld func(pIter unsafe.Pointer, iVal int32, ppValue unsafe.Pointer) int32
var Sqlite3changesetNew func(pIter unsafe.Pointer, iVal int32, ppValue unsafe.Pointer) int32
var Sqlite3changesetConflict func(pIter unsafe.Pointer, iVal int32, ppValue unsafe.Pointer) int32
var Sqlite3changesetFkConflicts func(pIter unsafe.Pointer, pnOut unsafe.Pointer) int32
var Sqlite3changesetFinalize func(pIter unsafe.Pointer) int32
var Sqlite3changesetInvert func(nIn int32, pIn unsafe.Pointer, pnOut unsafe.Pointer, ppOut unsafe.Pointer) int32
var Sqlite3changesetConcat func(nA int32, pA unsafe.Pointer, nB int32, pB unsafe.Pointer, pnOut unsafe.Pointer, ppOut unsafe.Pointer) int32
var Sqlite3changegroupNew func(pp unsafe.Pointer) int32
var Sqlite3changegroupSchema func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, zDb string) int32
var Sqlite3changegroupAdd func(arg0 unsafe.Pointer, nData int32, pData unsafe.Pointer) int32
var Sqlite3changegroupAddChange func(arg0 unsafe.Pointer, arg1 unsafe.Pointer) int32
var Sqlite3changegroupOutput func(arg0 unsafe.Pointer, pnData unsafe.Pointer, ppData unsafe.Pointer) int32
var Sqlite3changegroupDelete func(arg0 unsafe.Pointer)
var Sqlite3changesetApply func(dB unsafe.Pointer, nChangeset int32, pChangeset unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, pCtx unsafe.Pointer) int32
var Sqlite3changesetApplyV2 func(dB unsafe.Pointer, nChangeset int32, pChangeset unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, pCtx unsafe.Pointer, ppRebase unsafe.Pointer, pnRebase unsafe.Pointer, flags int32) int32
var Sqlite3changesetApplyV3 func(dB unsafe.Pointer, nChangeset int32, pChangeset unsafe.Pointer, arg0 unsafe.Pointer, arg1 unsafe.Pointer, pCtx unsafe.Pointer, ppRebase unsafe.Pointer, pnRebase unsafe.Pointer, flags int32) int32
var Sqlite3rebaserCreate func(ppNew unsafe.Pointer) int32
var Sqlite3rebaserConfigure func(arg0 unsafe.Pointer, nRebase int32, pRebase unsafe.Pointer) int32
var Sqlite3rebaserRebase func(arg0 unsafe.Pointer, nIn int32, pIn unsafe.Pointer, pnOut unsafe.Pointer, ppOut unsafe.Pointer) int32
var Sqlite3rebaserDelete func(p unsafe.Pointer)
var Sqlite3changesetApplyStrm func(dB unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer, pCtx unsafe.Pointer) int32
var Sqlite3changesetApplyV2Strm func(dB unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer, pCtx unsafe.Pointer, ppRebase unsafe.Pointer, pnRebase unsafe.Pointer, flags int32) int32
var Sqlite3changesetApplyV3Strm func(dB unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer, arg1 unsafe.Pointer, arg2 unsafe.Pointer, pCtx unsafe.Pointer, ppRebase unsafe.Pointer, pnRebase unsafe.Pointer, flags int32) int32
var Sqlite3changesetConcatStrm func(arg0 unsafe.Pointer, pInA unsafe.Pointer, arg1 unsafe.Pointer, pInB unsafe.Pointer, arg2 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3changesetInvertStrm func(arg0 unsafe.Pointer, pIn unsafe.Pointer, arg1 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3changesetStartStrm func(pp unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer) int32
var Sqlite3changesetStartV2Strm func(pp unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer, flags int32) int32
var Sqlite3sessionChangesetStrm func(pSession unsafe.Pointer, arg0 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3sessionPatchsetStrm func(pSession unsafe.Pointer, arg0 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3changegroupAddStrm func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, pIn unsafe.Pointer) int32
var Sqlite3changegroupOutputStrm func(arg0 unsafe.Pointer, arg1 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3rebaserRebaseStrm func(pRebaser unsafe.Pointer, arg0 unsafe.Pointer, pIn unsafe.Pointer, arg1 unsafe.Pointer, pOut unsafe.Pointer) int32
var Sqlite3sessionConfig func(op int32, pArg unsafe.Pointer) int32
