// Code generated by sqlitegen. DO NOT EDIT.
package capi

import (
	"github.com/bnema/purego"
)

// Sqlite3ConfigAddr symbol address, loaded by Register.
var Sqlite3ConfigAddr uintptr

// Sqlite3Config1 calls sqlite3_config with 1 argument(s) via SyscallN.
func Sqlite3Config1(arg0 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3ConfigAddr, arg0)
	return r1
}

// Sqlite3Config2 calls sqlite3_config with 2 argument(s) via SyscallN.
func Sqlite3Config2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3ConfigAddr, arg0, arg1)
	return r1
}

// Sqlite3Config3 calls sqlite3_config with 3 argument(s) via SyscallN.
func Sqlite3Config3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3ConfigAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3DBConfigAddr symbol address, loaded by Register.
var Sqlite3DBConfigAddr uintptr

// Sqlite3DBConfig2 calls sqlite3_db_config with 2 argument(s) via SyscallN.
func Sqlite3DBConfig2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3DBConfigAddr, arg0, arg1)
	return r1
}

// Sqlite3DBConfig3 calls sqlite3_db_config with 3 argument(s) via SyscallN.
func Sqlite3DBConfig3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3DBConfigAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3DBConfig4 calls sqlite3_db_config with 4 argument(s) via SyscallN.
func Sqlite3DBConfig4(arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3DBConfigAddr, arg0, arg1, arg2, arg3)
	return r1
}

// Sqlite3SnprintfAddr symbol address, loaded by Register.
var Sqlite3SnprintfAddr uintptr

// Sqlite3Snprintf3 calls sqlite3_snprintf with 3 argument(s) via SyscallN.
func Sqlite3Snprintf3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3SnprintfAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3Snprintf4 calls sqlite3_snprintf with 4 argument(s) via SyscallN.
func Sqlite3Snprintf4(arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3SnprintfAddr, arg0, arg1, arg2, arg3)
	return r1
}

// Sqlite3Snprintf5 calls sqlite3_snprintf with 5 argument(s) via SyscallN.
func Sqlite3Snprintf5(arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr, arg4 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3SnprintfAddr, arg0, arg1, arg2, arg3, arg4)
	return r1
}

// Sqlite3TestControlAddr symbol address, loaded by Register.
var Sqlite3TestControlAddr uintptr

// Sqlite3TestControl1 calls sqlite3_test_control with 1 argument(s) via SyscallN.
func Sqlite3TestControl1(arg0 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3TestControlAddr, arg0)
	return r1
}

// Sqlite3TestControl2 calls sqlite3_test_control with 2 argument(s) via SyscallN.
func Sqlite3TestControl2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3TestControlAddr, arg0, arg1)
	return r1
}

// Sqlite3TestControl3 calls sqlite3_test_control with 3 argument(s) via SyscallN.
func Sqlite3TestControl3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3TestControlAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3StrAppendfAddr symbol address, loaded by Register.
var Sqlite3StrAppendfAddr uintptr

// Sqlite3StrAppendf2 calls sqlite3_str_appendf with 2 argument(s) via SyscallN.
func Sqlite3StrAppendf2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3StrAppendfAddr, arg0, arg1)
	return r1
}

// Sqlite3StrAppendf3 calls sqlite3_str_appendf with 3 argument(s) via SyscallN.
func Sqlite3StrAppendf3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3StrAppendfAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3StrAppendf4 calls sqlite3_str_appendf with 4 argument(s) via SyscallN.
func Sqlite3StrAppendf4(arg0 uintptr, arg1 uintptr, arg2 uintptr, arg3 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3StrAppendfAddr, arg0, arg1, arg2, arg3)
	return r1
}

// Sqlite3LogAddr symbol address, loaded by Register.
var Sqlite3LogAddr uintptr

// Sqlite3Log2 calls sqlite3_log with 2 argument(s) via SyscallN.
func Sqlite3Log2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3LogAddr, arg0, arg1)
	return r1
}

// Sqlite3Log3 calls sqlite3_log with 3 argument(s) via SyscallN.
func Sqlite3Log3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3LogAddr, arg0, arg1, arg2)
	return r1
}

// Sqlite3VtabConfigAddr symbol address, loaded by Register.
var Sqlite3VtabConfigAddr uintptr

// Sqlite3VtabConfig2 calls sqlite3_vtab_config with 2 argument(s) via SyscallN.
func Sqlite3VtabConfig2(arg0 uintptr, arg1 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3VtabConfigAddr, arg0, arg1)
	return r1
}

// Sqlite3VtabConfig3 calls sqlite3_vtab_config with 3 argument(s) via SyscallN.
func Sqlite3VtabConfig3(arg0 uintptr, arg1 uintptr, arg2 uintptr) uintptr {
	r1, _, _ := purego.SyscallN(Sqlite3VtabConfigAddr, arg0, arg1, arg2)
	return r1
}
