// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/purego-sqlite/internal/ports/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStmt creates a new instance of MockStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStmt {
	mock := &MockStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStmt is an autogenerated mock type for the Stmt type
type MockStmt struct {
	mock.Mock
}

type MockStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStmt) EXPECT() *MockStmt_Expecter {
	return &MockStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStmt
func (_mock *MockStmt) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStmt_Expecter) Close() *MockStmt_Close_Call {
	return &MockStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStmt_Close_Call) Run(run func()) *MockStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStmt_Close_Call) Return(err error) *MockStmt_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStmt_Close_Call) RunAndReturn(run func() error) *MockStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockStmt
func (_mock *MockStmt) Exec(args ...any) (in.Result, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 in.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...any) (in.Result, error)); ok {
		return returnFunc(args...)
	}
	if returnFunc, ok := ret.Get(0).(func(...any) in.Result); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...any) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStmt_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockStmt_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - args ...any
func (_e *MockStmt_Expecter) Exec(args ...interface{}) *MockStmt_Exec_Call {
	return &MockStmt_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{}, args...)...)}
}

func (_c *MockStmt_Exec_Call) Run(run func(args ...any)) *MockStmt_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockStmt_Exec_Call) Return(result in.Result, err error) *MockStmt_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockStmt_Exec_Call) RunAndReturn(run func(args ...any) (in.Result, error)) *MockStmt_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NumInput provides a mock function for the type MockStmt
func (_mock *MockStmt) NumInput() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NumInput")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockStmt_NumInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumInput'
type MockStmt_NumInput_Call struct {
	*mock.Call
}

// NumInput is a helper method to define mock.On call
func (_e *MockStmt_Expecter) NumInput() *MockStmt_NumInput_Call {
	return &MockStmt_NumInput_Call{Call: _e.mock.On("NumInput")}
}

func (_c *MockStmt_NumInput_Call) Run(run func()) *MockStmt_NumInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStmt_NumInput_Call) Return(n int) *MockStmt_NumInput_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStmt_NumInput_Call) RunAndReturn(run func() int) *MockStmt_NumInput_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockStmt
func (_mock *MockStmt) Query(args ...any) (in.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 in.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...any) (in.Rows, error)); ok {
		return returnFunc(args...)
	}
	if returnFunc, ok := ret.Get(0).(func(...any) in.Rows); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(in.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...any) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStmt_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockStmt_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - args ...any
func (_e *MockStmt_Expecter) Query(args ...interface{}) *MockStmt_Query_Call {
	return &MockStmt_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{}, args...)...)}
}

func (_c *MockStmt_Query_Call) Run(run func(args ...any)) *MockStmt_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockStmt_Query_Call) Return(rows in.Rows, err error) *MockStmt_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockStmt_Query_Call) RunAndReturn(run func(args ...any) (in.Rows, error)) *MockStmt_Query_Call {
	_c.Call.Return(run)
	return _c
}
